/**
 * What a recording is, and the one fact about it that is never allowed to be
 * ambiguous: whether a person actually said these words.
 *
 * Pure functions and no store, for the reason `assignments/model` gives — the
 * questions here (how long has this been running, what does the transcript
 * read as, is this real) are the ones that go quietly wrong, and a pure
 * function is the only kind a test can pin down.
 *
 * Days are `YYYY-MM-DD` and times are minutes from midnight, matching the
 * agenda. Durations *inside* a recording are milliseconds, because a segment
 * at "minute 37" of a meeting is not a wall-clock fact and must not be one:
 * a recording that is paused, or interrupted and resumed, has a timeline of
 * its own that does not care what the clock did in between.
 */

import { clock, keyOf, type DayKey } from "../agenda/model";

/* ── Provenance: the honesty field ───────────────────────────────────── */

/**
 * Where the words came from. Two answers, both spelled out, no default.
 *
 * `src/lib/speech`'s `listen()` silently swaps in the simulated provider when
 * the Web Speech API is missing or fails, and that provider *invents* a
 * transcript — a scripted monologue with invented numbers in it. For the
 * notepad that is a fair demo of speech-to-prose. Here it would mean a
 * recorder that hands somebody a meeting they never had and then writes the
 * appointments it "heard" into their calendar. So provenance is a required
 * field on every recording and a stamp on every segment, and the recorder
 * never reaches the simulated provider except when a caller asks for it by
 * name.
 */
export type Provenance = "microphone" | "simulated";

/** The line that fabricated text can never be separated from. */
export const SIMULATED_BANNER =
  "[simulated transcript — these words were generated by the demo speech provider. Nobody said them. Do not file anything from this.]";

export interface Segment {
  /**
   * Milliseconds of *recorded* time since the recording began. Time while
   * stopped or interrupted is not counted, so a meeting resumed after a
   * reload still reads 00:00 → the end without an hour-long hole in it.
   */
  at: number;
  text: string;
  /**
   * Present, and only ever `true`, on fabricated words.
   *
   * On the segment rather than only on the recording, because segments get
   * copied — into a document, into a re-run of the model, into a clipboard —
   * and a mark that does not travel with the words is not a mark.
   */
  simulated?: true;
}

/** Why a recording is no longer running. Absent means it still is. */
export type Ended =
  | "stopped"
  | "interrupted"
  | "no-recogniser"
  | "microphone-denied"
  | "discarded";

export const ENDED_LABELS: Record<Ended, string> = {
  stopped: "Stopped",
  interrupted: "Cut off — the tab closed or reloaded while recording",
  "no-recogniser": "Stopped — the browser gave up transcribing",
  "microphone-denied": "Stopped — no microphone",
  discarded: "Thrown away",
};

export interface Recording {
  id: string;
  provenance: Provenance;
  /** Epoch ms of the first start. */
  startedAt: number;
  /** The day it started on, for the agenda and for grouping. */
  day: DayKey;
  /** Minutes from midnight it started at. */
  startMinute: number;
  segments: Segment[];
  /**
   * Recorded milliseconds from runs that have already finished. The run
   * happening right now is `runningSince`; `elapsedMs` adds the two.
   */
  ms: number;
  /** Epoch ms this run began, or null when nothing is running. */
  runningSince: number | null;
  /**
   * Epoch ms of the last word heard, or of the last start.
   *
   * This is the last proof the tab was alive, which is what a recording
   * interrupted by a crash has to be closed at — the alternative is counting
   * the three days the laptop was shut as recording time.
   */
  heardUntil: number;
  ended?: Ended;
  endedAt?: number;
  /** What the person called it. The model's title goes on the document. */
  title?: string;
  /** The document made from it, once one exists. */
  projectId?: string;
  /** Milliseconds since the epoch; last edit wins. */
  updatedAt: number;
}

/* ── Making one ──────────────────────────────────────────────────────── */

/**
 * `id` and `now` are arguments rather than read in here so this file stays
 * pure — and so a test can put the clock at 23:59 and check the day key.
 */
export function newRecording(
  id: string,
  provenance: Provenance,
  now: Date,
): Recording {
  const at = now.getTime();
  return {
    id,
    provenance,
    startedAt: at,
    day: keyOf(now),
    startMinute: now.getHours() * 60 + now.getMinutes(),
    segments: [],
    ms: 0,
    runningSince: at,
    heardUntil: at,
    updatedAt: at,
  };
}

/* ── Reading one ─────────────────────────────────────────────────────── */

export const isLive = (recording: Recording): boolean =>
  recording.ended === undefined;

/** Recorded milliseconds so far, including the run in progress. */
export function elapsedMs(recording: Recording, now: number): number {
  if (recording.runningSince === null) return recording.ms;
  return recording.ms + Math.max(0, now - recording.runningSince);
}

/** `mm:ss`, or `h:mm:ss` once it has been running an hour. */
export function clockOf(ms: number): string {
  const total = Math.max(0, Math.floor(ms / 1000));
  const seconds = String(total % 60).padStart(2, "0");
  const minutes = Math.floor(total / 60) % 60;
  const hours = Math.floor(total / 3600);
  if (hours === 0) return `${minutes}:${seconds}`;
  return `${hours}:${String(minutes).padStart(2, "0")}:${seconds}`;
}

/** Where a segment sits in the recording, for a timestamped document. */
export const stampOf = (segment: Segment): string => clockOf(segment.at);

export const wordCount = (recording: Recording): number =>
  recording.segments.reduce(
    (total, segment) => total + (segment.text.trim().split(/\s+/).filter(Boolean).length),
    0,
  );

export const isSimulated = (recording: Recording): boolean =>
  recording.provenance === "simulated" ||
  recording.segments.some((segment) => segment.simulated);

/**
 * The transcript as one string — the only string that ever leaves this store.
 *
 * A simulated recording gets the banner welded to the front of it. Everything
 * downstream (the model prompt, the document body, a copy-paste into an
 * email) therefore carries the warning by construction, rather than by every
 * caller remembering to check a flag.
 */
export function transcriptOf(recording: Recording): string {
  const body = recording.segments
    .map((segment) => segment.text.trim())
    .filter(Boolean)
    .join("\n");
  if (!isSimulated(recording)) return body;
  return `${SIMULATED_BANNER}\n\n${body}`;
}

/** The same thing with `mm:ss` in front of each line, for the document. */
export function stampedTranscriptOf(recording: Recording): string {
  const body = recording.segments
    .filter((segment) => segment.text.trim())
    .map((segment) => `${stampOf(segment)}  ${segment.text.trim()}`)
    .join("\n");
  if (!isSimulated(recording)) return body;
  return `${SIMULATED_BANNER}\n\n${body}`;
}

/**
 * The gate anything that writes to the agenda, the assignments or the account
 * must pass first.
 *
 * It throws rather than returning false on purpose: a boolean gets `if`ed
 * around and then forgotten in the next refactor, whereas a throw that
 * reaches a user is a bug report. Nothing derived from a simulated recording
 * is allowed to become a real appointment.
 */
export function assertReal(recording: Recording): void {
  if (!isSimulated(recording)) return;
  throw new Error(
    "This transcript was simulated, not heard. Nothing can be filed from it.",
  );
}

/**
 * A name for a recording that has not been given one, or for a file list.
 *
 * `isSimulated`, not `provenance === "simulated"`. A recording can be opened
 * against a real microphone and still hold fabricated segments — a demo run
 * resumed, a session that fell back — and testing the recording's own label
 * left those looking exactly like a meeting somebody had.
 */
export function defaultTitle(recording: Recording): string {
  const when = `${recording.day} ${clock(recording.startMinute)}`;
  return isSimulated(recording)
    ? `Simulated recording ${when}`
    : `Recording ${when}`;
}

/**
 * What to call it on screen.
 *
 * A simulated recording says so in its name whatever it has been called. Only
 * `defaultTitle()` used to carry the mark, so renaming one took it off — and a
 * fabricated meeting sat in the list looking exactly like a meeting somebody
 * had. The mark goes in front rather than behind because a list clips the end
 * of a long title, and this is the half that has to survive.
 */
export function titleOf(recording: Recording): string {
  const given = recording.title?.trim();
  if (!given) return defaultTitle(recording);
  if (!isSimulated(recording)) return given;
  return /^simulated\b/i.test(given) ? given : `Simulated — ${given}`;
}

/** Newest first — what a list of past recordings wants. */
export const byNewest = (a: Recording, b: Recording): number =>
  b.startedAt - a.startedAt;
